import EditorJS from '@editorjs/editorjs';
// import Header from '@editorjs/header';
import List from '@editorjs/list';
import ImageTool from "@editorjs/image";
import RawTool from '@editorjs/raw';
import LinkTool from '@editorjs/link';
import Paragraph from '@editorjs/paragraph';
import CodeTool from '@editorjs/code';
import Embed from '@editorjs/embed';
import AttachesTool from '@editorjs/attaches';
import Table from '@editorjs/table';
// import Quote from '@editorjs/quote';
import Underline from '@editorjs/underline';
import Delimiter from '@editorjs/delimiter';
import InlineCode from '@editorjs/inline-code';
import TextVariantTune from '@editorjs/text-variant-tune';
import Marker from '@editorjs/marker';
import FontSize from 'editorjs-inline-font-size-tool';
import edtsHTML from 'editorjs-html';
import * as EditorJSLayout from 'editorjs-layout';
import * as EditorJSStyle from 'editorjs-style';
import ColorPicker from 'editorjs-color-picker';
import HeaderAlignment from 'editorjs-header-with-alignment';
import ParagraphAlignment from 'editorjs-paragraph-with-alignment';
import Quote from "@cychann/editorjs-quote";
import Title from "title-editorjs";
import AnyButton from "editorjs-button";

window.EditorJSLayout = EditorJSLayout;
window.edtsHTML = edtsHTML;
window.EditorJSStyle = EditorJSStyle;
window.ColorPicker = ColorPicker;
window.HeaderAlignment = HeaderAlignment;
window.ParagraphAlignment = ParagraphAlignment;
window.Quote = Quote;
window.Title = Title;
window.AnyButton = AnyButton;
// window.Header = Header;
window.List = List;
window.RawTool = RawTool;
window.EditorJS = EditorJS;
window.ImageTool = ImageTool;
window.LinkTool = LinkTool;
window.Paragraph = Paragraph;
window.CodeTool = CodeTool;
window.Embed = Embed;
window.AttachesTool = AttachesTool;
window.Table = Table;
// window.Quote = Quote;
window.Underline = Underline;
window.Delimiter = Delimiter;
window.InlineCode = InlineCode;
window.TextVariantTune = TextVariantTune;
window.Marker = Marker;
window.FontSize = FontSize;