import EditorJS from '@editorjs/editorjs';
import ImageTool from "@editorjs/image";
import RawTool from '@editorjs/raw';
import LinkTool from '@editorjs/link';
import Paragraph from '@editorjs/paragraph';
import CodeTool from '@editorjs/code';
import Embed from '@editorjs/embed';
import AttachesTool from '@editorjs/attaches';
import Table from '@editorjs/table';
import Underline from '@editorjs/underline';
import Delimiter from '@editorjs/delimiter';
import InlineCode from '@editorjs/inline-code';
import TextVariantTune from '@editorjs/text-variant-tune';
import Marker from '@editorjs/marker';
import FontSize from 'editorjs-inline-font-size-tool';
import edtsHTML from 'editorjs-html';
import * as EditorJSLayout from 'editorjs-layout';
import * as EditorJSStyle from 'editorjs-style';
import ColorPicker from 'editorjs-color-picker';
import HeaderAlignment from 'editorjs-header-with-alignment';
import ParagraphAlignment from 'editorjs-paragraph-with-alignment';
import Quote from "@cychann/editorjs-quote";
import Title from "title-editorjs";
import AnyButton from "editorjs-button";
import EditorjsList from '@editorjs/list';
import editorjsNestedChecklist from '@calumk/editorjs-nested-checklist';
import InlineImage from 'editorjs-inline-image';
import EJLaTeX from 'editorjs-latex';
import MermaidTool from 'editorjs-mermaid';
import TelegramPost from 'editorjs-telegram-post';
import AudioPlayer from 'editorjs-audio-player';
import Undo from 'editorjs-undo';
import DragDrop from "editorjs-drag-drop";
import IndentTune from 'editorjs-indent-tune';

window.IndentTune = IndentTune;
window.DragDrop = DragDrop;
window.Undo = Undo;
window.AudioPlayer = AudioPlayer;
window.TelegramPost = TelegramPost;
window.MermaidTool = MermaidTool;
window.EJLaTeX = EJLaTeX;
window.InlineImage = InlineImage;
window.EditorJSLayout = EditorJSLayout;
window.edtsHTML = edtsHTML;
window.EditorJSStyle = EditorJSStyle;
window.ColorPicker = ColorPicker;
window.HeaderAlignment = HeaderAlignment;
window.ParagraphAlignment = ParagraphAlignment;
window.EditorjsNestedChecklist = editorjsNestedChecklist;
window.Quote = Quote;
window.Title = Title;
window.AnyButton = AnyButton;
window.EditorjsList = EditorjsList;
window.RawTool = RawTool;
window.EditorJS = EditorJS;
window.ImageTool = ImageTool;
window.LinkTool = LinkTool;
window.Paragraph = Paragraph;
window.CodeTool = CodeTool;
window.Embed = Embed;
window.AttachesTool = AttachesTool;
window.Table = Table;
window.Underline = Underline;
window.Delimiter = Delimiter;
window.InlineCode = InlineCode;
window.TextVariantTune = TextVariantTune;
window.Marker = Marker;
window.FontSize = FontSize;